### Get all books
GET http://localhost:3000/api/books

### Get one book
GET http://localhost:3000/api/books/2

### Create a new book
POST http://localhost:3000/api/books
Content-Type: application/json

{
    "Author": "test2",
    "Title": "test2",
    "Pages": 123,
    "Description": "test2",
    "Image": "./src/image/test"
}

### Modify a book
PUT http://localhost:3000/api/books/3
Content-Type: application/json

{
    "Author": "test3",
    "Title": "test3",
    "Pages": 123,
    "Description": "test3",
    "Image": "./src/image/test"
}

### Delete a book
DELETE http://localhost:3000/api/books/2

### Get chuck data
GET http://localhost:3000/api/external