### Get all objects
GET http://localhost:3000/api/menu/books

### Get one object
GET http://localhost:3000/api/menu/books/2

### Create a new object
POST http://localhost:3000/api/menu/books
Content-Type: application/json

{
    "Author": "test2",
    "Title": "test2",
    "Pages": 123,
    "Description": "test2",
    "Image": "./src/image/test"
}

### Modify an object
PUT http://localhost:3000/api/menu/books/3
Content-Type: application/json

{
    "Author": "test3",
    "Title": "test3",
    "Pages": 123,
    "Description": "test3",
    "Image": "./src/image/test"
}

### Delete an object
DELETE http://localhost:3000/api/menu/books/20